Home: Install pwntools
Disable moreutils install for a minute there because of this collision

error: builder for '/nix/store/vmbzi46nx22znh6gczlb6xf5wd5xf8wg-home-manager-path.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/5z3sjp9r463i3siif58hq5wj5jmy5m98-python3.12-pwntools-4.13.1/bin/errno' and `/nix/store/i2zywd0y302lyppnmpdhwcg3dnhgbbq0-moreutils-0.69/bin/errno'